### ISSUE TITLE
Expand inner variable in dependencies.bash

### ISSUE THREAD

**Issue by HughP** [unimatrixdoc/MLKA-Bash-data#11]
@unimatrixdoc can you try and expand `${x}` when it is embedded in `$y`  I can't see to make it work... 

Look for the embedded variable in my data file in the repo root. 

I have also bee looking at this link: http://stackoverflow.com/questions/2634590/bash-script-variable-inside-variable

```
 #!/bin/bash

IFS=$'\n'
for i in dependencies.data; do
x=($(csvfix read_dsv -csv -smq -s '|' -f 1 dependencies.data ))
y=($(csvfix read_dsv -csv -smq -s '|' -f 2 dependencies.data ))
z=($(csvfix read_dsv -csv -smq -s '|' -f 3 dependencies.data ))

unset $IFS
	for (( i=0; i < ${#x[@]}; i++ )); do
	    if type ${x} &>/dev/null; then
	        echo
	        echo ${y[$i]}
	        echo
	    else
	    	echo
	        echo ${z[$i]}
	        echo
	        exit 1
	    fi
	done
done
```

**Comment by unimatrixdoc** [comment]
Nice link. Oh I see what you're saying. I'll see what I can do. :)

**Comment by HughP** [comment]
Run the most current code! I fixed this but forgot to close the issue. I got it to expand.
